[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python app_production.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
FLASK_ENV = "production"
PORT = "5001"
